const express = require('express')
const dotenv = require('dotenv')
const connection = require('./shared/connect')
const fromauthentication = require('./routes/authentication')
const fromitem = require('./routes/item')
const frominventory = require('./routes/inventory')
const order = require('./routes/payment')
const checkout = require('./routes/checkout')
const cors = require('cors') 
const app = express()
app.use(express.json())
dotenv.config()
connection.connect()
app.use(cors())
app.use('/',(req,res,next) =>{
    next();
})
app.use('/',fromauthentication)
app.use('/items',fromitem)
app.use('/inventory',frominventory)
app.use('/order',order) 
app.use('/payment/successful',checkout)
app.listen(process.env.PORT || 5000)